version: '2.21'
services:
    web:
        build: ./web
        ports:
            - 3000:3000
        environment:
            - FLASK_ENV=production
        depends_on:
            - api
    api:
        build: ./api
        ports:
            - 8080:8080
