version: '2.21'
services:
    web:
        build: ./web
        ports:
            - 3000:80
        environment:
            - FLASK_ENV=production
        depends_on:
            - api
    api:
        build: ./api
        ports:
            - 5000:5000
